default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRESQL_USER_NAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

development:
  <<: *default
  database: food_tracks_dev

test:
  <<: *default
  database: food_tracks_test
